### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tucnak** [fblue/broeselhud_blue#1]
What's the license you distribute broeselhud_blue under? Can you please add a licensing file?

**Comment by fblue** [comment]
broeselhud_blue is not published under a license and I won't add a licensing file. It's not mandatory and I don't see the need for it either.

**Comment by tucnak** [comment]
Well, it's currently published on a opensource hub, which makes it an opensource project. Inb4 using it, I'd want to understand what I'm eligable to do and what I'm not. Currently it could be treated as Public Domain contribution, which could be used without a credit back to you, which might be a little bit disappointing for you, so I started this thread.

Public Domain? Okay, there we go!

**Comment by fblue** [comment]
According to this site http://choosealicense.com/no-license/ you seem to be mistaken on the effect that the absence of a license has. Anyway, I just don't think a license is too important for a TF2 HUD edit.

**Comment by tucnak** [comment]
Alright, gotcha.
