### ISSUE TITLE
Scoreboard isn't showing everything.

### ISSUE THREAD

**Issue by thesnowman** [fblue/broeselhud_blue#2]
Hi, I just updated to the latest version that you have here, and since then I have been getting very little information on the scoreboard. I really like this hud and hope to keep using it as much as possible.  

![2016-01-12_00001](https://cloud.githubusercontent.com/assets/1450320/12283473/8349ba68-b974-11e5-883b-ef5f57d8ff45.jpg)

**Comment by tucnak** [comment]
:+1:

**Comment by fblue** [comment]
Should be fixed now.
