### ISSUE TITLE
12th player cut off in scoreboard

### ISSUE THREAD

**Issue by PixelArray** [fblue/broeselhud_blue#3]
Title explains everything. On BLU in this screenshot, the 12th player is cut off. Display is 16:10 and 1280x800.

![2016-01-16_00002](https://cloud.githubusercontent.com/assets/12025067/12378906/7419ff66-bd12-11e5-90d8-9d7c98070cad.jpg)

**Comment by fblue** [comment]
This HUD is optimised for 1680x1050 because most people use high resolutions. It's impossible to make a HUD work the same at high and low resolutions, there will always be minor differences or bugs.
