### ISSUE TITLE
Add an option for the old overheal style?

### ISSUE THREAD

**Issue by DicksMcLong** [fblue/broeselhud_blue#6]
I prefer the look of the old one, with the bar appearing over the health instead of it just turning green.  Could you add that as an option in a separate folder, like Broeselhud_blue_extras?

**Comment by googlebleh** [comment]
First, I'd like to compliment your username.

But to address your question: Have you tried grabbing the file from an older commit? If you can identify the commit hash from [here](https://github.com/fblue/broeselhud_blue/commits/master), you can do `git checkout <commit hash> <path to file>` and either see if it still works, or you can just grab the lines that make the old style and apply them to the current version of the file.

**Comment by DicksMcLong** [comment]
I didn't try switching to the older version, but it's not buggy or anything.  I just prefer the older look with the bar instead of just changing the color to green.  I liked the visual reference to see how much overheal someone had without having to look directly at the number (which is also a reason why I use broeselhud to begin with).  Seeing a bar at 50% is faster than reading 100/200 HP, to me.

I also looked through some of the commits and couldn't find the file associated with teammates' health bars, unless I'm just being dumb.

**Comment by fblue** [comment]
It's not worth it for me to add this as an option considering there's not even a handful of people who would use it. You'll have to use the spectatorguihealth.res file from before [this commit](https://github.com/fblue/broeselhud_blue/commit/94094da8ffef95c0b25a21b880d990057ec7d4cd).
