### ISSUE TITLE
Needs a compatibility update for Meet Your Match

### ISSUE THREAD

**Issue by DicksMcLong** [fblue/broeselhud_blue#7]
HUD is non-functional because of the way TF2 handles custom UIs now. 

From the update page: 

- In order to reduce crashing and broken UI elements after updates, custom HUDs now must explicitly specify the version of the TF UI with which they are compatible.
- Custom HUD files must now be installed as add-ons under the tf/custom/ folder. Loose .res files extracted to the game directory will not be loaded.
- Custom HUDs must now contain a file named "info.vdf" in their root folder, with the key "ui_version" set to the TF UI version with which they are compatible.
- The current TF UI version is 1.
- Non-HUD add-ons under tf/custom/ will continue to work without an "info.vdf" file, but may not load .res files.

**Comment by fblue** [comment]
Added basic functionality for the MM update today. There are a lot of things I will have to edit later.
